server:
  port: 8082
  servlet:
    context-path: /
spring:
  datasource:
    #    name: test
    url: jdbc:mysql://127.0.0.1:3306/springdb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#    注解形式sql
#      mybatis:
#        type-aliases-package:domain

##该配置节点为独立的节点，若这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.common.domin #注意：对应实体类的路径

  ## Redis 配置
  ## Redis数据库索引（默认为0）
redis:
  #数据库索引
  database: 0
  host: 127.0.0.1
  port: 6379
#  password: 123456
  jedis:
    pool:
      #最大连接数
      max-active: 8
      #最大阻塞等待时间(负数表示没限制)
      max-wait: -1
      #最大空闲
      max-idle: 8
      #最小空闲ap
      min-idle: 0
  #连接超时时间(毫秒)
  timeout: 10000