--1.建表u_user语句sql
CREATE TABLE `u_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `name` VARCHAR(256) DEFAULT NULL COMMENT '姓名',
  `age` INT(11) DEFAULT NULL COMMENT '年龄',
  `sex` VARCHAR(4) DEFAULT NULL COMMENT '性别',
  PRIMARY KEY (`id`)
) ENGINE=INNODB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

--2.查询
select * from u_user;